version: 2

jobs:
    build:
        docker:
            - image: gallileo/radarr-cci-primary:4.8
        steps:
            - checkout
            - run: git submodule update --init --recursive
            - run:
                name: Build
                command: ./build.sh
            - run:
                name: Testing
                command: ./test.sh Linux Unit
            - store_test_results:
                path: _tests/reports/
