blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://discord.gg/AD3UP37
    about: Chat with users and devs on support and setup related topics.
  - name: Support via Reddit
    url: https://reddit.com/r/radarr
    abbout: Discuss and search thru support topics.
